export const ADD_VEHICLE = "ADD_VEHICLE";
export const RETRIEVE_VEHICLES = "RETRIEVE_VEHICLES";
export const RETRIEVE_VEHICLE_BY_ID = "RETRIEVE_VEHICLE_BY_ID";
export const RETRIEVE_BOOKED_VEHICLES = "RETRIEVE_BOOKED_VEHICLES";
export const RETRIEVE_AVAILABLE_VEHICLES = "RETRIEVE_AVAILABLE_VEHICLES";
export const GET_NUMBER_OF_VEHICLES_RENTED ="GET_NUMBER_OF_VEHICLES_RENTED";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";